# Generated by Django 4.2.6 on 2023-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_usuarios_documento_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('f_nac', models.DateField()),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
