# Generated by Django 4.2.1 on 2023-10-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_anuncios_asistencia_campana_cartera_direccion_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campana',
            old_name='correo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='f_nac',
            new_name='f_final',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='documento',
            new_name='operador',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='telefono',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='apellido',
            new_name='tipo',
        ),
    ]
