# Generated by Django 4.2.1 on 2023-10-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_rename_correo_campana_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncios',
            old_name='correo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='anuncios',
            old_name='f_nac',
            new_name='f_final',
        ),
        migrations.RenameField(
            model_name='anuncios',
            old_name='apellido',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='anuncios',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='anuncios',
            name='telefono',
        ),
        migrations.AddField(
            model_name='anuncios',
            name='imagen',
            field=models.ImageField(null=True, upload_to='anuncios'),
        ),
    ]
