# Generated by Django 4.2.1 on 2023-10-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_anuncios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
